name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Este flujo de trabajo se ejecutará en un entorno Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala las dependencias listadas en requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # Ejecuta las pruebas unitarias
